data:
  raw:
    dir: data/raw
    name: data2
    path: ${data.raw.dir}/${data.raw.name}.csv
  merged:
    dir: data/merged
    name: merged.csv
    path: ${data.merged.dir}/${data.merged.name}
  processed:
    dir: data/processed
model_path: model/model.pkl
process:
  feature: quality
  test_size: 0.2
train:
  hyperparameters:
    svm__kernel:
      - linear
    svm__C:
      - 0.1
      - 1
      - 10
    svm__gamma:
      - 0.1
      - 1
      - 10
  grid_search:
    cv: 2
    scoring: accuracy
    verbose: 3
s3:
  raw:
    new:
      bucket: kestra-mlops-demo
      file_name: data2.csv
      object_key: new/${s3.raw.new.file_name}
      local_path: data/raw/${s3.raw.new.file_name}
    old:
      bucket: kestra-mlops-demo
      prefix: old 
      local_path: data/raw
  processed:
    bucket: kestra-mlops-demo
    object_key: processed.pkl
detect:
  data:
    current: data/current.csv
    reference: data/reference.csv
    
  columns:
    numerical_features:
      - col_0
      - col_1
      - col_2
      - col_3
      - col_5
  dates:
    start: "2011-02-01"
    end: "2011-02-28"
    # - ["2011-03-01", "2011-03-31"]
    # - ["2011-04-01", "2011-04-30"]
    # - ["2011-05-01", "2011-05-31"]
    # - ["2011-06-01", "2011-06-30"]
    # - ["2011-07-01", "2011-07-31"]

  report:
    get_ratio: true   
    path: data_drift_report.html
